### PR TITLE
the env option must be optionnal

### LINKED ISSUE #25: Error An option named "env" already exists with sf3.3
Updating with sf3.3 generates an error with the command `consume`

```console
                                                        
  [Symfony\Component\Console\Exception\LogicException]  
  An option named "env" already exists.                 
                                                        

Exception trace:
 () at /srv/vendor/symfony/symfony/src/Symfony/Component/Console/Input/InputDefinition.php:244
 Symfony\Component\Console\Input\InputDefinition->addOption() at /srv/vendor/symfony/symfony/src/Symfony/Component/Console/Input/InputDefinition.php:230
 Symfony\Component\Console\Input\InputDefinition->addOptions() at /srv/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:319
 Symfony\Component\Console\Command\Command->mergeApplicationDefinition() at /srv/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:218
 Symfony\Component\Console\Command\Command->run() at /srv/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:887
 Symfony\Component\Console\Application->doRunCommand() at /srv/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:223
 Symfony\Component\Console\Application->doRun() at /srv/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:81
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /srv/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:130
 Symfony\Component\Console\Application->run() at /srv/bin/console:28

wisembly:amqp:consume [--rpc] [--disable-verbosity-propagation] [--poll-interval POLL-INTERVAL] [--memory-limit MEMORY-LIMIT] [--env ENV] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <gate>
```

It seems that this [hack](https://github.com/Wisembly/AMQPBundle/blob/master/src/Command/ConsumerCommand.php#L73-L77) does not work anymore

### PR DESCRIPTION
**Pull request by krichprollsch**
fixes #25

### CODE REVIEW

File: src/Command/ConsumerCommand.php [hunk 1]
```diff
@@ -91,7 +85,7 @@ protected function execute(InputInterface $input, OutputInterface $output)
             $provider,
             $producer,
             $this->consolePath,
-            $input->getOption('env'),
+            $input->hasOption('env') ? $input->getOption('env') : null,
             true === $input->getOption('disable-verbosity-propagation') ? OutputInterface::VERBOSITY_QUIET : $output->getVerbosity()
```
Comment (Taluu) [inline src/Command/ConsumerCommand.php]: test also if `env` is not available. does not make sense if not disabling AND not having env.

Comment (Taluu) [inline src/Command/ConsumerCommand.php]: nevermind, it's the verbosity not the env
